### ISSUE TITLE
watchers/receptors

### ISSUE THREAD

**Issue by Firedrake969** [Firedrake969/gopher-brain#13]
watch certain parts of the "brain" and then trigger other parts of the "brain" based on the watchers
probably made manually

**Comment by liam4** [comment]
```
brain1 (listener to brain2) --> brain3
brainA, brainB --> brain2 (adder)
# now when the result of adding brainA and brainB changes, brain3 gets triggered
# with the result, right?
```

**Comment by Firedrake969** [comment]
Kinda, sure
I was thinking about like environmental cues and responses, but that would be pretty sweet too

let's just not make this into skynet :P (I wish it were even a little closer xD)

**Comment by liam4** [comment]
![gopher-watcher](https://cloud.githubusercontent.com/assets/9948030/15095568/1fb0744e-14a3-11e6-9cfc-d11011cdf4ca.png)

could be entirely misinterpreting how this project works though ^^;

**Comment by liam4** [comment]
Watcher could be rewritten to say "when something in the general vicinity lights up, light up" which is kinda similar but I guess in a more neuron-friendly way..

**Comment by Firedrake969** [comment]
I was thinking something more like http://prntscr.com/b1jj4f to emulate an environment - like you send a signal to move your arm, your arm hits something, and then that response is returned to a different center (i.e. motion center --> environment --> pain center)

**Comment by Firedrake969** [comment]
halfway done - sensors (such as human eyes) are complete

**Comment by Firedrake969** [comment]
See other issues now
