### ISSUE TITLE
learn what ffmpeg actually does

### ISSUE THREAD

**Issue by Firedrake969** [Firedrake969/gopher-brain#17]
also how to use it besides just google/stackoverflow

**Comment by ethanhs** [comment]
FWIW:
ffmpeg is a program that one can use to deal with video. FF (Fast forward) MPEG (Moving Pictures Experts Group) is the root of the name. Essentially, movie studios wanted a good video format, got a lot of smart people to write a standard, and they did. FFMPEG allows you to record video/audio and convert between video/audio formats. It uses the amazing libavcodec (which FFMPEG developers maintain), which also powers the VLC media player. The library does the grunt work of encoding and decoding formats.

**Comment by Firedrake969** [comment]
Cool, thanks!  What's left for me to do know is figure out the command format (and all the flags, yay)

**Comment by Firedrake969** [comment]
not like I use it any more
